FROM python:3.9-slim

# PYTHONUNBUFFERED keeps Python from buffering our stdout
# PYTHONPATH tells where to find local python package
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /app

# WORKDIR /app/{service_name}
WORKDIR /app/web
COPY . .

# Install deps
RUN pip install --upgrade pip \
    pip install --no-cache-dir -r requirements.txt
