FROM osgeo/gdal:ubuntu-small-3.1.3

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /app

RUN mkdir -p /app/compass
ADD requirements.txt /app/compass

RUN apt install -y build-essential libssl-dev libffi-dev python3-dev \
    wget python3-distutils

# Install pip
RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python get-pip.py \
    && rm get-pip.py

WORKDIR /app/compass

# Install deps
RUN pip install --upgrade pip \
    pip install -r requirements.txt
